import type { AnimationSpec } from '../src/lib/animation';

export function auditedGeometrySpec(): AnimationSpec {
  return {
    schemaVersion: 5,
    title: 'Sine as a unit-circle projection',
    summary:
      'A rotating unit-circle point transfers its vertical coordinate to the sine graph.',
    durationSeconds: 10,
    assumptions: ['Angles are measured in radians.'],
    intent: {
      learningGoal:
        'Connect the vertical coordinate on the unit circle to sin(theta).',
      hook: 'One rotating point controls a distant wave.',
      takeaway: 'The sine graph records the rotating point height.',
    },
    direction: {
      preset: 'geometric-proof',
      frame: '16:9',
      pacing: 'balanced',
      textPolicy: { maxWordsPerObject: 8, maxSimultaneousText: 2 },
    },
    cinematography: { scene: 'static', emphasis: 'clean' },
    knowledgeMap: [
      {
        id: 'unit-circle-coordinate',
        concept:
          'A unit-circle point has coordinates (cos(theta), sin(theta)).',
        dependsOn: [],
        misconception: 'The angle is not the arc length of a non-unit circle.',
      },
      {
        id: 'sine-projection',
        concept: 'The sine value is the vertical coordinate of that point.',
        dependsOn: ['unit-circle-coordinate'],
        misconception: 'The sine value is not the horizontal coordinate.',
      },
    ],
    curriculum: [
      {
        id: 'identify-angle',
        learningJob: 'Identify theta on the unit circle.',
        dependsOn: ['unit-circle-coordinate'],
        visualEvidence:
          'An angle arc and rotating radius share the same theta.',
        notationBudget: 1,
      },
      {
        id: 'project-height',
        learningJob: 'Read the rotating point vertical coordinate.',
        dependsOn: ['identify-angle', 'sine-projection'],
        visualEvidence:
          'A horizontal connector preserves the point height across the frame.',
        notationBudget: 2,
      },
      {
        id: 'trace-wave',
        learningJob: 'Recognize the accumulated heights as a sine graph.',
        dependsOn: ['project-height'],
        visualEvidence: 'The connector meets y=sin(x) at the matching height.',
        notationBudget: 2,
      },
    ],
    mathDossier: {
      coreClaim:
        'For a unit-circle point at angle theta, its vertical coordinate equals sin(theta).',
      invariants: [
        'The rotating point remains two coordinate units from the displayed center.',
        'The connector endpoint has the same vertical coordinate as the point.',
      ],
      commonMisreading:
        'Cosine is the horizontal coordinate; sine is the vertical coordinate.',
      visualProof:
        'Move a point along the circle, mark theta, and carry its height with a horizontal line to y=sin(x).',
      definitions: [
        {
          concept: 'Unit-circle coordinates',
          statement: 'P(theta)=(cos(theta), sin(theta)) for real theta.',
        },
      ],
      derivationSteps: [
        'A radius-one point at angle theta has coordinates (cos(theta), sin(theta)).',
        'Therefore the point height and the sine-curve ordinate are both sin(theta).',
      ],
      checks: [
        {
          claim: 'At theta=pi/2 the point height is one.',
          method: 'Substitute theta=pi/2.',
          expected: 'sin(pi/2)=1',
        },
      ],
      limitations: ['The display samples one revolution.'],
    },
    style: {
      background: '#0B0D14',
      palette: ['#6A9BCC', '#D97757', '#FAF9F5'],
      camera: 'Fixed geometric proof frame',
    },
    objects: [
      {
        id: 'axes',
        kind: 'axes',
        region: 'graph',
        importance: 'context',
      },
      {
        id: 'unit-circle',
        kind: 'circle',
        region: 'graph',
        importance: 'hero',
        center: [0, 0],
        radius: 2,
        color: '#6A9BCC',
      },
      {
        id: 'rotating-point',
        kind: 'point',
        region: 'graph',
        importance: 'hero',
        position: [2, 0],
        color: '#D97757',
      },
      {
        id: 'angle-arc',
        kind: 'arc',
        region: 'graph',
        importance: 'supporting',
        center: [0, 0],
        radius: 0.65,
        startAngle: 0,
        sweepAngle: 1.0472,
        color: '#D4A27F',
      },
      {
        id: 'projection-line',
        kind: 'line',
        region: 'graph',
        importance: 'supporting',
        start: [1, 1.732],
        end: [4, 1.732],
        color: '#D97757',
      },
      {
        id: 'direction-arrow',
        kind: 'arrow',
        region: 'graph',
        importance: 'context',
        start: [0, 0],
        end: [1, 1.732],
        color: '#FAF9F5',
      },
      {
        id: 'sine-wave',
        kind: 'curve',
        region: 'graph',
        importance: 'hero',
        expr: 'sin(x)',
        domain: [0, 6],
        color: '#62D9C3',
      },
      {
        id: 'sine-formula',
        kind: 'formula',
        region: 'formula',
        importance: 'supporting',
        expr: 'y=\\sin(\\theta)',
        color: '#FAF9F5',
      },
    ],
    shots: [
      {
        id: 'hook',
        beat: 'hook',
        purpose: 'Reveal the circle, angle and starting point.',
        startAt: 0,
        endAt: 2,
        focusRef: 'unit-circle',
        transition: 'build',
        acceptance: [
          'The circle, point and angle arc are simultaneously visible.',
        ],
      },
      {
        id: 'mechanism',
        beat: 'mechanism',
        purpose: 'Move the point and preserve its height with a connector.',
        startAt: 2,
        endAt: 7,
        focusRef: 'rotating-point',
        transition: 'morph',
        acceptance: [
          'The point motion and horizontal projection are explicit.',
        ],
      },
      {
        id: 'payoff',
        beat: 'payoff',
        purpose: 'Resolve the transferred height as the sine graph.',
        startAt: 7,
        endAt: 10,
        focusRef: 'sine-wave',
        transition: 'hold',
        acceptance: ['The formula and completed curve remain readable.'],
      },
    ],
    timeline: [
      {
        id: 'circle-in',
        shotId: 'hook',
        at: 0,
        op: 'draw',
        ref: 'unit-circle',
        runTime: 1,
        ease: 'smooth',
      },
      {
        id: 'point-in',
        shotId: 'hook',
        at: 1,
        op: 'fade_in',
        ref: 'rotating-point',
        runTime: 1,
        ease: 'smooth',
      },
      {
        id: 'angle-in',
        shotId: 'hook',
        at: 1,
        op: 'draw',
        ref: 'angle-arc',
        runTime: 1,
        ease: 'smooth',
      },
      {
        id: 'point-around-circle',
        shotId: 'mechanism',
        at: 2,
        op: 'move_along',
        ref: 'rotating-point',
        pathRef: 'unit-circle',
        runTime: 2,
        ease: 'linear',
      },
      {
        id: 'projection-in',
        shotId: 'mechanism',
        at: 4,
        op: 'draw',
        ref: 'projection-line',
        runTime: 1,
        ease: 'smooth',
      },
      {
        id: 'wave-in',
        shotId: 'mechanism',
        at: 5,
        op: 'draw',
        ref: 'sine-wave',
        runTime: 2,
        ease: 'smooth',
      },
      {
        id: 'formula-in',
        shotId: 'payoff',
        at: 7,
        op: 'write',
        ref: 'sine-formula',
        runTime: 1,
        ease: 'smooth',
      },
      {
        id: 'payoff-hold',
        shotId: 'payoff',
        at: 8,
        op: 'hold',
        ref: 'sine-wave',
        runTime: 2,
        ease: 'linear',
      },
    ],
    layout: { regions: 'top|bottom' },
    dependencies: ['Manim Community', 'LaTeX'],
    notes: ['The connector and point share one semantic color.'],
  };
}
