import type { AnimationStatus } from '@/lib/animation';
import { m } from '@/paraglide/messages.js';
import {
  CreatorWorkspace as CreatorWorkspaceComponent,
  type CreatorWorkspaceCopy,
} from '@/components/creator-workspace';

export function CreatorWorkspace({
  locale,
  initialAnimationId,
}: {
  locale: string;
  initialAnimationId?: string;
}) {
  const statuses: Record<AnimationStatus, string> = {
    draft: m['creator.status.draft'](),
    generating_spec: m['creator.status.generating_spec'](),
    awaiting_approval: m['creator.status.awaiting_approval'](),
    generating_code: m['creator.status.generating_code'](),
    code_ready: m['creator.status.code_ready'](),
    queued: m['creator.status.queued'](),
    rendering: m['creator.status.rendering'](),
    canceled: m['creator.status.canceled'](),
    completed: m['creator.status.completed'](),
    failed: m['creator.status.failed'](),
  };
  const copy: CreatorWorkspaceCopy = {
    title: m['creator.title'](),
    subtitle: m['creator.subtitle'](),
    newAnimation: m['creator.new_animation'](),
    gallery: m['landing.nav.gallery'](),
    workflow: m['landing.nav.workflow'](),
    history: m['creator.history'](),
    historyEmpty: m['creator.history_empty'](),
    openHistory: m['creator.open_history'](),
    closeSidebar: m['creator.close_sidebar'](),
    collapseSidebar: m['creator.collapse_sidebar'](),
    expandSidebar: m['creator.expand_sidebar'](),
    userCenter: m['creator.user_center'](),
    credits: m['creator.credits'](),
    guestNavigation: m['creator.guest_navigation'](),
    viewPricing: m['landing.nav.pricing'](),
    signIn: m['common.sign.sign_in_title'](),
    moreActions: m['creator.more_actions'](),
    renameAnimation: m['creator.rename_animation'](),
    renamePlaceholder: m['creator.rename_placeholder'](),
    renameSave: m['creator.rename_save'](),
    renameCancel: m['creator.rename_cancel'](),
    renameEmpty: m['creator.rename_empty'](),
    renameTooLong: m['creator.rename_too_long'](),
    deleteAnimation: m['creator.delete_animation'](),
    deleteConfirm: (title) => m['creator.delete_confirm']({ title }),
    promptPlaceholder: m['creator.prompt_placeholder'](),
    promptLabel: m['creator.prompt_label'](),
    create: m['creator.create'](),
    revise: m['creator.revise'](),
    signInToCreate: m['creator.sign_in_to_create'](),
    subject: m['creator.subject'](),
    model: m['creator.model'](),
    characters: m['creator.characters'](),
    welcomeEyebrow: m['creator.welcome_eyebrow'](),
    welcomeTitle: m['creator.welcome_title'](),
    welcomeDescription: m['creator.welcome_description'](),
    tipsTitle: m['creator.tips_title'](),
    tips: [
      m['creator.tip_formula'](),
      m['creator.tip_viewport'](),
      m['creator.tip_sequence'](),
      m['creator.tip_style'](),
    ],
    processing: m['creator.processing'](),
    workspaceLabel: m['creator.workspace_label'](),
    sectionLabel: m['creator.section_label'](),
    conversationEyebrow: m['creator.conversation_eyebrow'](),
    userLabel: m['creator.user_label'](),
    assistantLabel: m['creator.assistant_label'](),
    suggestionGroups: [
      {
        value: 'suggested',
        label: m['creator.suggestions.suggested'](),
        prompts: [
          m['creator.suggestion.suggested_1'](),
          m['creator.suggestion.suggested_2'](),
          m['creator.suggestion.suggested_3'](),
        ],
      },
      {
        value: 'curves',
        label: m['creator.suggestions.curves'](),
        prompts: [
          m['creator.suggestion.curves_1'](),
          m['creator.suggestion.curves_2'](),
          m['creator.suggestion.curves_3'](),
        ],
      },
      {
        value: 'proofs',
        label: m['creator.suggestions.proofs'](),
        prompts: [
          m['creator.suggestion.proofs_1'](),
          m['creator.suggestion.proofs_2'](),
          m['creator.suggestion.proofs_3'](),
        ],
      },
      {
        value: 'physics',
        label: m['creator.suggestions.physics'](),
        prompts: [
          m['creator.suggestion.physics_1'](),
          m['creator.suggestion.physics_2'](),
          m['creator.suggestion.physics_3'](),
        ],
      },
    ],
    conversation: m['creator.conversation'](),
    specification: m['creator.specification'](),
    code: m['creator.code'](),
    video: m['creator.video'](),
    preview: m['creator.preview'](),
    previewEmpty: m['creator.preview_empty'](),
    previewPlaybackError: m['creator.preview_playback_error'](),
    playPreview: m['creator.play_preview'](),
    retryPlayback: m['creator.retry_playback'](),
    approve: m['creator.approve'](),
    retryPlan: m['creator.retry_plan'](),
    retryCode: m['creator.retry_code'](),
    retryRender: m['creator.retry_render'](),
    approvalDescription: m['creator.approval_description'](),
    duration: m['creator.duration'](),
    assumptions: m['creator.assumptions'](),
    formulas: m['creator.formulas'](),
    visualStyle: m['creator.visual_style'](),
    scenes: m['creator.scenes'](),
    purpose: m['creator.purpose'](),
    math: m['creator.math'](),
    visuals: m['creator.visuals'](),
    actions: m['creator.actions'](),
    layout: m['creator.layout'](),
    areas: m['creator.areas'](),
    dependencies: m['creator.dependencies'](),
    notes: m['creator.notes'](),
    pipelineLabel: m['creator.pipeline_label'](),
    pipelineSpec: m['creator.pipeline.spec'](),
    pipelineApprove: m['creator.pipeline.approve'](),
    pipelineProcess: m['creator.pipeline.process'](),
    pipelineDone: m['creator.pipeline.done'](),
    planningEyebrow: m['creator.planning.eyebrow'](),
    planningTitle: m['creator.planning.title'](),
    planningDescription: m['creator.planning.description'](),
    planningSemanticMap: m['creator.planning.semantic_map'](),
    planningLiveSummary: m['creator.planning.live_summary'](),
    planningPhases: {
      understanding: m['creator.planning.phase.understanding'](),
      structuring: m['creator.planning.phase.structuring'](),
      auditing: m['creator.planning.phase.auditing'](),
      finalizing: m['creator.planning.phase.finalizing'](),
    },
    resizePanels: m['creator.panel.resize'](),
    noCode: m['creator.no_code'](),
    noVideo: m['creator.no_video'](),
    codeReadyTitle: m['creator.code_ready_title'](),
    codeReadyDescription: m['creator.code_ready_description'](),
    renderQueued: m['creator.render_queued'](),
    codeReadyMessage: m['creator.message.code_ready'](),
    renderCompletedMessage: m['creator.message.render_completed'](),
    failed: m['creator.failed'](),
    failureDescription: m['creator.failure_description'](),
    requestFailed: m['creator.request_failed'](),
    renameFailed: m['creator.rename_failed'](),
    deleteFailed: m['creator.delete_failed'](),
    copyCode: m['creator.copy_code'](),
    downloadCode: m['creator.download_code'](),
    copied: m['creator.copied'](),
    versions: m['creator.versions'](),
    loading: m['creator.loading'](),
    loadFailed: m['creator.load_failed'](),
    modelAuto: m['creator.model.auto'](),
    modelAutoDescription: m['creator.model.auto_description'](),
    modelFree: m['creator.model.free'](),
    modelStarter: m['creator.model.starter'](),
    modelPro: m['creator.model.pro'](),
    modelStarterRequired: m['creator.model.starter_required'](),
    modelProRequired: m['creator.model.pro_required'](),
    modelUpgrade: m['creator.model.upgrade'](),
    modelLoading: m['creator.model.loading'](),
    modelLoadFailed: m['creator.model.load_failed'](),
    modelRetryLoad: m['creator.model.retry_load'](),
    modelUnavailable: m['creator.model.unavailable'](),
    modelUnavailableShort: m['creator.model.unavailable_short'](),
    curatedModels: {
      kieGemini36Flash: {
        label: m['creator.model.kie_gemini_36_flash.label'](),
        description: m['creator.model.kie_gemini_36_flash.description'](),
      },
      kieGrok45: {
        label: m['creator.model.kie_grok_45.label'](),
        description: m['creator.model.kie_grok_45.description'](),
      },
      kieGemini31Pro: {
        label: m['creator.model.kie_gemini_31_pro.label'](),
        description: m['creator.model.kie_gemini_31_pro.description'](),
      },
      kieGpt52: {
        label: m['creator.model.kie_gpt_52.label'](),
        description: m['creator.model.kie_gpt_52.description'](),
      },
      kieGpt55: {
        label: m['creator.model.kie_gpt_55.label'](),
        description: m['creator.model.kie_gpt_55.description'](),
      },
      kieClaudeSonnet46: {
        label: m['creator.model.kie_claude_sonnet_46.label'](),
        description: m['creator.model.kie_claude_sonnet_46.description'](),
      },
      kieClaudeOpus47: {
        label: m['creator.model.kie_claude_opus_47.label'](),
        description: m['creator.model.kie_claude_opus_47.description'](),
      },
    },
    failureMessages: {
      UPSTREAM_SATURATED: m['creator.failure.upstream_saturated'](),
      UPSTREAM_TIMEOUT: m['creator.failure.upstream_timeout'](),
      UPSTREAM_UNAVAILABLE: m['creator.failure.upstream_unavailable'](),
      UPSTREAM_AUTH: m['creator.failure.upstream_auth'](),
      UPSTREAM_QUOTA: m['creator.failure.upstream_quota'](),
      INVALID_OUTPUT: m['creator.failure.invalid_output'](),
      STREAM_INTERRUPTED: m['creator.failure.stream_interrupted'](),
      RENDER_FAILED: m['creator.failure.render_failed'](),
      PRO_REQUIRED: m['creator.failure.pro_required'](),
      INSUFFICIENT_CREDITS: m['creator.failure.insufficient_credits'](),
      BUSY: m['creator.failure.busy'](),
      UNKNOWN: m['creator.failure.unknown'](),
    },
    subjects: [
      { value: 'general', label: m['creator.subject.general']() },
      { value: 'math', label: m['creator.subject.math']() },
      { value: 'physics', label: m['creator.subject.physics']() },
      {
        value: 'computer-science',
        label: m['creator.subject.computer_science'](),
      },
      { value: 'biology', label: m['creator.subject.biology']() },
      { value: 'chemistry', label: m['creator.subject.chemistry']() },
      { value: 'economics', label: m['creator.subject.economics']() },
    ],
    statuses,
    entryTemplate: m['creator.entry.template'](),
    entryFormula: m['creator.entry.formula'](),
    entryDescription: m['creator.entry.description'](),
    templateEyebrow: m['creator.template.eyebrow'](),
    templateTitle: m['creator.template.title'](),
    templateDescription: m['creator.template.description'](),
    templateUse: m['creator.template.use'](),
    templateEmpty: m['creator.template.empty'](),
    formulaEyebrow: m['creator.formula.eyebrow'](),
    formulaTitle: m['creator.formula.title'](),
    formulaDescription: m['creator.formula.description'](),
    formulaInput: m['creator.formula.input'](),
    formulaPlaceholder: m['creator.formula.placeholder'](),
    formulaIntent: m['creator.formula.intent'](),
    formulaIntentPlaceholder: m['creator.formula.intent_placeholder'](),
    formulaSymbols: m['creator.formula.symbols'](),
    formulaPreview: m['creator.formula.preview'](),
    formulaContinue: m['creator.formula.continue'](),
    mathObjectType: m['creator.formula.object_type'](),
    mathTypes: {
      function: m['creator.formula.type.function'](),
      integral: m['creator.formula.type.integral'](),
      series: m['creator.formula.type.series'](),
      matrix: m['creator.formula.type.matrix'](),
    },
    legacyArchive: m['creator.legacy_archive'](),
    saveSpec: m['creator.spec.save'](),
    savingSpec: m['creator.spec.saving'](),
    objectsLabel: m['creator.spec.objects'](),
    timelineLabel: m['creator.spec.timeline'](),
    directorIntent: m['creator.spec.director_intent'](),
    learningGoal: m['creator.spec.learning_goal'](),
    hook: m['creator.spec.hook'](),
    takeaway: m['creator.spec.takeaway'](),
    shotPlan: m['creator.spec.shot_plan'](),
    acceptance: m['creator.spec.acceptance'](),
    cinematography: m['creator.spec.cinematography'](),
    formulaParts: m['creator.spec.formula_parts'](),
    mathDossier: m['creator.spec.math_dossier'](),
    coreClaim: m['creator.spec.core_claim'](),
    invariants: m['creator.spec.invariants'](),
    commonMisreading: m['creator.spec.common_misreading'](),
    visualProof: m['creator.spec.visual_proof'](),
    startTime: m['creator.spec.start_time'](),
    runTime: m['creator.spec.run_time'](),
    ease: m['creator.spec.ease'](),
    restoreVersion: m['creator.version.restore'](),
    renderStages: {
      queued: m['creator.render.stage.queued'](),
      validating: m['creator.render.stage.validating'](),
      compiling: m['creator.render.stage.compiling'](),
      transcoding: m['creator.render.stage.transcoding'](),
      reviewing: m['creator.render.stage.reviewing'](),
      uploading: m['creator.render.stage.uploading'](),
    },
    cancelRender: m['creator.render.cancel'](),
    canceledRender: m['creator.render.canceled'](),
    downloadVideo: m['creator.video.download'](),
    publishGallery: m['creator.gallery.publish'](),
    publishedGallery: m['creator.gallery.published'](),
    editAgain: m['creator.edit_again'](),
    specSaved: m['creator.spec.saved'](),
    restoreSucceeded: m['creator.version.restored'](),
    actionFailed: m['creator.action_failed'](),
  };

  return (
    <CreatorWorkspaceComponent
      copy={copy}
      locale={locale}
      initialAnimationId={initialAnimationId}
    />
  );
}
